pipelines:
  default:
    - parallel:
        - step:
            name: Build and test web app
            image: node:10.15.0
            script:
              - make -C services/webapp install
              - make -C services/webapp build
            caches:
              - yarn
              - webappnode
        - step:
            name: Test backend
            image: atlassian/default-image:2
            script:
              - echo "test" > VERSION
              - make -C services/backend test PROJECT_NAME=test ENV_STAGE=test
            services:
              - docker
            caches:
              - docker
        - step:
            name: Test async-workers
            image: python:3.8
            script:
              - pip install pipenv --upgrade
              - echo "test" > VERSION
              - make -C services/workers install-python-ci PROJECT_NAME=test ENV_STAGE=test
              - make -C services/workers test PROJECT_NAME=test ENV_STAGE=test
            services:
              - docker
            caches:
              - pip
              - docker

definitions:
  services:
    docker:
      memory: 1024
  caches:
    yarn: /usr/local/share/.cache/yarn
    webappnode: ./services/webapp/node_modules
    pipenv: ./services/webapp/node_modules
