pipelines:
  default:
    - parallel:
        - step:
            name: Push code to CodeCommit
            clone:
              depth: full
            script:
              - git remote add codecommit "$CODE_COMMIT_REPO"
              - git push -u codecommit "$BITBUCKET_BRANCH"
              - git push codecommit --tags

        - step:
            name: Build and test web app
            image: apptension/awsb-base
            script:
              - make -C services/webapp install
              - make -C services/webapp build
            caches:
              - yarn
              - webappnode

        - step:
            name: Test backend
            image: apptension/awsb-base
            script:
              - echo "test" > VERSION
              - make -C services/backend test PROJECT_NAME=test ENV_STAGE=test
            services:
              - docker
            caches:
              - docker

        - step:
            name: Test async-workers
            image: apptension/awsb-base
            script:
              - echo "test" > VERSION
              - make -C services/workers test PROJECT_NAME=test ENV_STAGE=test
            services:
              - docker
              - db
            caches:
              - pip
              - docker

definitions:
  services:
    docker:
      memory: 1024
    db:
      image: postgres:10.6
      environment:
        POSTGRES_USER: backend
        POSTGRES_PASSWORD: backend
        POSTGRES_DB: backend
  caches:
    yarn: /usr/local/share/.cache/yarn
    webappnode: ./services/webapp/node_modules
