stackName: "${self:custom.projectEnvName}-infra-functions"

iam:
  - Effect: "Allow"
    Action:
      - "codebuild:StartBuild"
    Resource:
      - "${self:custom.conf.entrypointCodeBuildProjectArn}"

environment:
  PROJECT_ENV_NAME: ${self:custom.projectEnvName}
  PROJECT_NAME: ${env:PROJECT_NAME}
  ENVIRONMENT_NAME: ${self:provider.stage}
  DEPLOY_BRANCHES: ${env:SB_DEPLOY_BRANCHES}
  WEBHOOK_SECRET: ${env:SB_WEBHOOK_SECRET}

vpc:
  securityGroupIds:
    - Fn::ImportValue: "${self:custom.projectEnvName}-lambdaSecurityGroupId"
  subnetIds:
    - Fn::ImportValue: "${self:custom.projectEnvName}-privateSubnetOneId"
    - Fn::ImportValue: "${self:custom.projectEnvName}-privateSubnetTwoId"

entrypointCodeBuildProjectArn: arn:aws:codebuild:${aws:region}:${aws:accountId}:project/${self:custom.projectEnvName}

esbuild:
  bundle: true
  minify: true
  target: [ 'es2020' ]
  sourcemap: true
  sourcesContent: false
  tsconfig: tsconfig.app.json
  define: { 'require.resolve': undefined }
