name: "Deploy to QA"

concurrency: QA

on:
  push:
    branches: ['master', 'feat/661-remove-code-commit']
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: 'true'

      - uses: ./.github/workflows/actions/deploy
        with:
          environment-name: 'qa'
          trigger-url: '${{ vars.SB_DEPLOY_TRIGGER_URL }}'
          trigger-secret: '${{ secrets.SB_DEPLOY_TRIGGER_SECRET }}'
