name: "Webapp-libs: Lint & test"

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ 16 ]
        webapp-lib-name:
          - webapp-core
          - webapp-api-client
          - webapp-contentful
          - webapp-crud-demo
          - webapp-documents
          - webapp-notifications
          - webapp-emails
          - webapp-finances
          - webapp-generative-ai
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/actions/setup

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=webapp-core...

      - name: Lint
        shell: bash
        run: node_modules/.bin/nx run webapp-core:lint

      - name: Type check
        shell: bash
        run: node_modules/.bin/nx run webapp-core:type-check

      - name: Test
        shell: bash
        run: node_modules/.bin/nx run webapp-core:test --watchAll=false --maxWorkers=20% --coverage

#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
