name: "Workers: Lint & test"

on:
  push:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/workflows/actions/initialize

      - shell: bash
        run: pnpm install
            --include-workspace-root
            --frozen-lockfile
            --filter=workers...

      - name: Lint workers
        shell: bash
        run: node_modules/.bin/nx run workers:lint

      - name: Test workers
        shell: bash
        run: node_modules/.bin/nx run workers:test

#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
